version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
  rendercontrol:
    build: .
    ports:
     - "5000:5000"
    environment:
     - FLASK_DEBUG=1
     - FLASK_APP=main.py
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: python ./main.py control
  rayserver:
    build:
      context: ./embree
      dockerfile: Dockerfile
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: ./result rays
  occlusionserver:
    build:
      context: ./embree
      dockerfile: Dockerfile
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: ./result occlusion
  shadeserver:
    build:
      context: ./shade
      dockerfile: Dockerfile
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: ./result   
  renderwriter:
    build: .
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: python ./writer.py
