version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.6.14-management
    #image: docker.dneg.com/rabbitmq:3.6.14-management
    ports:
      - "8082:15672"
  rendercontrol:
    image: docker.dneg.com/gfj/rendercontrol:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "5000:5000"
    environment:
     - FLASK_DEBUG=1
     - FLASK_APP=main.py
    volumes:
     - ".:/usr/src//app"
    links:
      - rabbitmq
      - influxdb
    command: python ./main.py control
  rayserver:
    image: docker.dneg.com/gfj/rayserver:latest
    build:
      context: .
      dockerfile: ./embree/Dockerfile
    volumes:
     - ".:/usr/src//app"
    links:
      - rabbitmq
    command: ./result rays
  occlusionserver:
    image: docker.dneg.com/gfj/rayserver:latest
    build:
      context: .
      dockerfile: ./embree/Dockerfile
    volumes:
     - ".:/usr/src//app"
    links:
      - rabbitmq
    command: ./result occlusion
  shadeserver:
    image: docker.dneg.com/gfj/shadeserver:latest  
    build:
      context: .
      dockerfile: ./shade/Dockerfile
    volumes:
     - ".:/usr/src//app"
    links:
      - rabbitmq
    command: ./result   
  renderwriter:
    image: docker.dneg.com/gfj/renderwriter:latest  
    build: .
    volumes:
     - ".:/usr/src//app"
    links:
      - rabbitmq
    command: python ./writer.py
  raygenerator:
    image: docker.dneg.com/gfj/raygenerator:latest  
    build:
      context: .
      dockerfile: ./raygenerator/Dockerfile
    volumes:
     - ".:/usr/src//app"
    links:
      - rabbitmq
    command: ./result 
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  influxdb:
    image: influxdb:1.4.3
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
     - INFLUXDB_DB=db
     - INFLUXDB_ADMIN_ENABLED=true
     - INFLUXDB_ADMIN_USER=admin
     - INFLUXDB_ADMIN_PASSWORD=admin
     - INFLUXDB_USER=influx
     - INFLUXDB_USER_PASSWORD=influx
  grafana:
    image: grafana/grafana:5.1.0
    ports:
     - "3000:3000"
    links:
     - influxdb 
    volumes:
     - ".:/var/lib/grafana"
