version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
  rendercontrol:
    build: .
    ports:
     - "5000:5000"
    environment:
     - FLASK_DEBUG=1
     - FLASK_APP=main.py
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: python ./main.py control
  rayserver:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: python ./rayserver.py
  occlusionserver:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: python ./rayserver.py
  shadeserver:
    build: .
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: python ./shadeserver.py   
  renderwriter:
    build: .
    volumes:
     - .:/usr/src//app
    links:
      - rabbitmq
    command: python ./writer.py
